### ISSUE TITLE
Crash due to passing float value to Qt

### ISSUE THREAD

**Issue by mod20388** [deragent/arXivFilter#11]
I am getting a consistent crash on Python 3.11 and PyQt 6.6:

```
Traceback (most recent call last):
  File "/home/mod20/.local/pipx/venvs/arxiv-filter/lib/python3.11/site-packages/arxiv_filter/ui/ArxivFilter.py", line 141, in parsedCallback
    self.tableFiltered.setEntries(filtered)
  File "/home/mod20/.local/pipx/venvs/arxiv-filter/lib/python3.11/site-packages/arxiv_filter/ui/ListView.py", line 52, in setEntries
    widget = ListEntry(entry, self._filtered)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mod20/.local/pipx/venvs/arxiv-filter/lib/python3.11/site-packages/arxiv_filter/ui/ListEntry.py", line 69, in __init__
    self.initUI()
  File "/home/mod20/.local/pipx/venvs/arxiv-filter/lib/python3.11/site-packages/arxiv_filter/ui/ListEntry.py", line 98, in initUI
    header_lo.setStretch(0, 0.01)
TypeError: setStretch(self, index: int, stretch: int): argument 2 has unexpected type 'float'
```

According to the [Qt doc](https://doc.qt.io/archives/qtforpython-5.12/PySide2/QtWidgets/QBoxLayout.html#PySide2.QtWidgets.PySide2.QtWidgets.QBoxLayout.setStretch) the setStretch function is only taking int values. Correcting the offending values in ui/ListEntry.pi seems to fix it.

**Comment by deragent** [comment]
Hi again,

indeed, looks like this was always a problem (I don't think the underlying QT has changed), but I assume in your newer QT version there is now type checking also in python (`setStretch(self, index: int, stretch: int)`).

I would assume the easy fix is, to just set the stretch here to 0, which is probably what is already happening implicitly when the value of `0.01` is  converted to an int by QT.

I will also look into this,
